DROP TABLE IF EXISTS fact_orders;

CREATE TABLE fact_orders (
    order_item_id               INTEGER PRIMARY KEY,
    order_id                    INTEGER,
    customer_id                 INTEGER,
    order_date                  TIMESTAMP,
    shipping_date                TIMESTAMP,
    days_for_shipping_real        SMALLINT,
    days_for_shipment_scheduled    SMALLINT,
    late_delivery_risk              BOOLEAN,
    delivery_status                  TEXT,
    shipping_mode                     TEXT,
    payment_type                       TEXT,
    market                              TEXT,
    order_region                        TEXT,
    order_country                       TEXT,
    order_state                         TEXT,
    order_city                          TEXT,
    order_zipcode                       INTEGER,
    order_status                        TEXT,
    customer_segment                    TEXT,
    customer_city                       TEXT,
    customer_state                      TEXT,
    customer_country                    TEXT,
    customer_zipcode                    INTEGER,
    category_id                         SMALLINT,
    category_name                       TEXT,
    department_id                       SMALLINT,
    department_name                     TEXT,
    product_card_id                     INTEGER,
    product_name                        TEXT,
    product_price                       NUMERIC(10,2),
    order_item_quantity                 SMALLINT,
    order_item_product_price            NUMERIC(10,2),
    order_item_discount                 NUMERIC(10,2),
    order_item_discount_rate            NUMERIC(5,4),
    order_item_profit_ratio             NUMERIC(6,4),
    sales                                NUMERIC(10,2),
    order_item_total                     NUMERIC(10,2),
    benefit_per_order                    NUMERIC(10,2),
    order_profit_per_order               NUMERIC(10,2),
    sales_per_customer                   NUMERIC(10,2),
    latitude                             NUMERIC(9,6),
    longitude                            NUMERIC(9,6)
);

INSERT INTO fact_orders
SELECT
    order_item_id::INTEGER,
    order_id::INTEGER,
    customer_id::INTEGER,
    to_timestamp(order_date, 'MM/DD/YYYY HH24:MI'),
    to_timestamp(shipping_date, 'MM/DD/YYYY HH24:MI'),
    days_for_shipping_real::SMALLINT,
    days_for_shipment_scheduled::SMALLINT,
    (late_delivery_risk = '1'),
    delivery_status,
    shipping_mode,
    type,
    market,
    order_region,
    order_country,
    order_state,
    order_city,
    NULLIF(order_zipcode, '')::INTEGER,
    order_status,
    customer_segment,
    customer_city,
    customer_state,
    customer_country,
    NULLIF(customer_zipcode, '')::INTEGER,
    category_id::SMALLINT,
    category_name,
    department_id::SMALLINT,
    department_name,
    product_card_id::INTEGER,
    product_name,
    product_price::NUMERIC(10,2),
    order_item_quantity::SMALLINT,
    order_item_product_price::NUMERIC(10,2),
    order_item_discount::NUMERIC(10,2),
    order_item_discount_rate::NUMERIC(5,4),
    order_item_profit_ratio::NUMERIC(6,4),
    sales::NUMERIC(10,2),
    order_item_total::NUMERIC(10,2),
    benefit_per_order::NUMERIC(10,2),
    order_profit_per_order::NUMERIC(10,2),
    sales_per_customer::NUMERIC(10,2),
    latitude::NUMERIC(9,6),
    longitude::NUMERIC(9,6)
FROM stg_supply_chain;
